### ISSUE TITLE
useToast autoClose option defaults to not close the toast and the tooltip documentation does not reflect this

### ISSUE THREAD

**Issue by cristidumitrescutotalsoft** [osstotalsoft/rocket-ui-ts#124]
### Latest version

- [X] I have tested the latest version

### Description

As the component works, the toast notification does not close. This can be an issue when switching from the react-toastify component to the Rocket-UI component.
For this feature request, the autoClose option for the useToast component may be given the default value.

### Examples
For the code: showToast(t("PersonWorkplaces.Updated"), "success");
![image](https://github.com/user-attachments/assets/5deae4af-47c0-423b-92f7-09a5c5af6380)
That remains on the screen

### Desired effect
The code shall have a default value for autoClose that closes the toast window

**Comment by cristidumitrescutotalsoft** [comment]
The error can be replicated on the storybook:
https://osstotalsoft.github.io/rocket-ui-ts/?path=/docs/components-feedback-toast--docs

**Comment by cristidumitrescutotalsoft** [comment]
###Examples
The problem was actually in the tooltip documentation. It did not reflect the actual default value. As shown below.
![image](https://github.com/user-attachments/assets/123e6f48-99bc-41cc-926c-79cc84362fe5)

###Desired effect
The code shall have a default value for autoClose of false and for that to be represented in the documentation.

**Comment by DCosti** [comment]
fixed in #125

**Comment by DCosti** [comment]
fixed in https://github.com/osstotalsoft/rocket-ui-ts/pull/125
