### ISSUE TITLE
The autocomplete options are not loaded. LoadOptions function is not called with user input

### ISSUE THREAD

**Issue by adrianchircats** [osstotalsoft/rocket-ui-ts#130]
### Latest version

- [X] I have tested the latest version

### Current behavior

loadOptions does not get called with user search input

### Expected behavior

loadOptions function to be called with user search input

### Steps to reproduce

Reproduced in this sandbox: https://codesandbox.io/p/sandbox/897stg

### Software Version

1. Storybook:
2. Rocket-UI:
3. Material UI:
4. React:
5. NPM/YARN:

**Comment by dragos-rosca** [comment]
Not a bug. This is the intended use. You are looking for `filterOptions`
