### ISSUE TITLE
Check if sonner is  better than react-toastify

### ISSUE THREAD

**Issue by DCosti** [osstotalsoft/rocket-ui-ts#56]
### Latest version

- [X] I have tested the latest version

### Description

Check if [sonner toast library](https://sonner.emilkowal.ski/) can be a better solution for toasts than [react-toastify](https://github.com/fkhadra/react-toastify)
The bundle wouldn't be affected:
![image](https://github.com/osstotalsoft/rocket-ui-ts/assets/41594981/c3573f61-d569-4f58-9239-c396d23fc93e)

**Comment by andra-sava** [comment]
Sonner is not the best fit for our project due to its limited customization options
