### ISSUE TITLE
TextField onChange is triggered without any user interaction

### ISSUE THREAD

**Issue by RobertBboghian** [osstotalsoft/rocket-ui-ts#83]
### Latest version

- [X] I have tested the latest version

### Current behavior

onChange is triggered at first render without any input from the user 

### Expected behavior

onChange to be triggered when a user actually change the value

### Software Version

1. Rocket-UI: 0.1.37
2. Material UI: 5.12.1

**Comment by alexandra-c** [comment]
Please offer a sandbox to help reproduce this issue.

**Comment by DCosti** [comment]
This is the correct behavior for [react-number-format](https://s-yadav.github.io/react-number-format/docs/props#onvaluechange-values-sourceinfo--) component.
